FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma/

RUN npm install 
RUN npx prisma generate

COPY . .

# Create .dockerignore to exclude .env file
RUN echo ".env" > .dockerignore

EXPOSE 8001

CMD ["npm", "run", "dev"]
