FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

# Install env-cmd globally
RUN npm install -g env-cmd

# Copy package files
COPY package*.json ./
COPY prisma ./prisma/

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npx prisma generate

# Copy the rest of the application
COPY . .

EXPOSE 8001
EXPOSE 9229

# Start the application
CMD ["npm", "run", "dev"]
