FROM node:20-slim

RUN apt-get update -y && apt-get install -y openssl

WORKDIR /app

COPY package.json package-lock.json ./
COPY prisma ./prisma/

# Install all dependencies including devDependencies
RUN npm install
RUN npx prisma generate

# Copy the rest of the application
COPY . .

EXPOSE 8001

# Use the development script
CMD ["npm", "run", "dev"]
